// Copyright 2020-2026 The streamIO Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: streamIO/proto/event.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Event_Type int32

const (
	Event_SubscribeEvent          Event_Type = 0
	Event_UnSubscribeEvent        Event_Type = 1
	Event_RetainMessageEvent      Event_Type = 2
	Event_ClientStatusChangeEvent Event_Type = 3
)

// Enum value maps for Event_Type.
var (
	Event_Type_name = map[int32]string{
		0: "SubscribeEvent",
		1: "UnSubscribeEvent",
		2: "RetainMessageEvent",
		3: "ClientStatusChangeEvent",
	}
	Event_Type_value = map[string]int32{
		"SubscribeEvent":          0,
		"UnSubscribeEvent":        1,
		"RetainMessageEvent":      2,
		"ClientStatusChangeEvent": 3,
	}
)

func (x Event_Type) Enum() *Event_Type {
	p := new(Event_Type)
	*p = x
	return p
}

func (x Event_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Event_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_streamIO_proto_event_proto_enumTypes[0].Descriptor()
}

func (Event_Type) Type() protoreflect.EnumType {
	return &file_streamIO_proto_event_proto_enumTypes[0]
}

func (x Event_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Event_Type.Descriptor instead.
func (Event_Type) EnumDescriptor() ([]byte, []int) {
	return file_streamIO_proto_event_proto_rawDescGZIP(), []int{0, 0}
}

type ClientStatusChangeEvent_Status int32

const (
	ClientStatusChangeEvent_Online  ClientStatusChangeEvent_Status = 0
	ClientStatusChangeEvent_Offline ClientStatusChangeEvent_Status = 1
)

// Enum value maps for ClientStatusChangeEvent_Status.
var (
	ClientStatusChangeEvent_Status_name = map[int32]string{
		0: "Online",
		1: "Offline",
	}
	ClientStatusChangeEvent_Status_value = map[string]int32{
		"Online":  0,
		"Offline": 1,
	}
)

func (x ClientStatusChangeEvent_Status) Enum() *ClientStatusChangeEvent_Status {
	p := new(ClientStatusChangeEvent_Status)
	*p = x
	return p
}

func (x ClientStatusChangeEvent_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientStatusChangeEvent_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_streamIO_proto_event_proto_enumTypes[1].Descriptor()
}

func (ClientStatusChangeEvent_Status) Type() protoreflect.EnumType {
	return &file_streamIO_proto_event_proto_enumTypes[1]
}

func (x ClientStatusChangeEvent_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientStatusChangeEvent_Status.Descriptor instead.
func (ClientStatusChangeEvent_Status) EnumDescriptor() ([]byte, []int) {
	return file_streamIO_proto_event_proto_rawDescGZIP(), []int{4, 0}
}

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte     `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Type Event_Type `protobuf:"varint,2,opt,name=type,proto3,enum=proto.Event_Type" json:"type,omitempty"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_streamIO_proto_event_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_streamIO_proto_event_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_streamIO_proto_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Event) GetType() Event_Type {
	if x != nil {
		return x.Type
	}
	return Event_SubscribeEvent
}

type SubscribeEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId      int64            `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Qos0StreamInfo *StreamInfoItem  `protobuf:"bytes,2,opt,name=qos0_stream_info,json=qos0StreamInfo,proto3" json:"qos0_stream_info,omitempty"`
	Qos1StreamInfo *StreamInfoItem  `protobuf:"bytes,3,opt,name=qos1_stream_info,json=qos1StreamInfo,proto3" json:"qos1_stream_info,omitempty"`
	Topic          map[string]int32 `protobuf:"bytes,4,rep,name=topic,proto3" json:"topic,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *SubscribeEvent) Reset() {
	*x = SubscribeEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_streamIO_proto_event_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEvent) ProtoMessage() {}

func (x *SubscribeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_streamIO_proto_event_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEvent.ProtoReflect.Descriptor instead.
func (*SubscribeEvent) Descriptor() ([]byte, []int) {
	return file_streamIO_proto_event_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeEvent) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *SubscribeEvent) GetQos0StreamInfo() *StreamInfoItem {
	if x != nil {
		return x.Qos0StreamInfo
	}
	return nil
}

func (x *SubscribeEvent) GetQos1StreamInfo() *StreamInfoItem {
	if x != nil {
		return x.Qos1StreamInfo
	}
	return nil
}

func (x *SubscribeEvent) GetTopic() map[string]int32 {
	if x != nil {
		return x.Topic
	}
	return nil
}

type UnSubscribeEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId int64    `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Topic     []string `protobuf:"bytes,4,rep,name=topic,proto3" json:"topic,omitempty"`
}

func (x *UnSubscribeEvent) Reset() {
	*x = UnSubscribeEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_streamIO_proto_event_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnSubscribeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnSubscribeEvent) ProtoMessage() {}

func (x *UnSubscribeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_streamIO_proto_event_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnSubscribeEvent.ProtoReflect.Descriptor instead.
func (*UnSubscribeEvent) Descriptor() ([]byte, []int) {
	return file_streamIO_proto_event_proto_rawDescGZIP(), []int{2}
}

func (x *UnSubscribeEvent) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *UnSubscribeEvent) GetTopic() []string {
	if x != nil {
		return x.Topic
	}
	return nil
}

type RetainMessageEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RetainMessageEvent) Reset() {
	*x = RetainMessageEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_streamIO_proto_event_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetainMessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetainMessageEvent) ProtoMessage() {}

func (x *RetainMessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_streamIO_proto_event_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetainMessageEvent.ProtoReflect.Descriptor instead.
func (*RetainMessageEvent) Descriptor() ([]byte, []int) {
	return file_streamIO_proto_event_proto_rawDescGZIP(), []int{3}
}

func (x *RetainMessageEvent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ClientStatusChangeEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionID int64                          `protobuf:"varint,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	Status    ClientStatusChangeEvent_Status `protobuf:"varint,2,opt,name=status,proto3,enum=proto.ClientStatusChangeEvent_Status" json:"status,omitempty"`
	BrokerId  int64                          `protobuf:"varint,3,opt,name=broker_id,json=brokerId,proto3" json:"broker_id,omitempty"`
}

func (x *ClientStatusChangeEvent) Reset() {
	*x = ClientStatusChangeEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_streamIO_proto_event_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientStatusChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStatusChangeEvent) ProtoMessage() {}

func (x *ClientStatusChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_streamIO_proto_event_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStatusChangeEvent.ProtoReflect.Descriptor instead.
func (*ClientStatusChangeEvent) Descriptor() ([]byte, []int) {
	return file_streamIO_proto_event_proto_rawDescGZIP(), []int{4}
}

func (x *ClientStatusChangeEvent) GetSessionID() int64 {
	if x != nil {
		return x.SessionID
	}
	return 0
}

func (x *ClientStatusChangeEvent) GetStatus() ClientStatusChangeEvent_Status {
	if x != nil {
		return x.Status
	}
	return ClientStatusChangeEvent_Online
}

func (x *ClientStatusChangeEvent) GetBrokerId() int64 {
	if x != nil {
		return x.BrokerId
	}
	return 0
}

var File_streamIO_proto_event_proto protoreflect.FileDescriptor

var file_streamIO_proto_event_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x4f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1a, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x4f, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xa9, 0x01, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x25, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x22, 0x65, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x0e,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x10, 0x00,
	0x12, 0x14, 0x0a, 0x10, 0x55, 0x6e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x52, 0x65, 0x74, 0x61, 0x69, 0x6e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x10, 0x02, 0x12, 0x1b,
	0x0a, 0x17, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x10, 0x03, 0x22, 0xa3, 0x02, 0x0a, 0x0e,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x3f, 0x0a,
	0x10, 0x71, 0x6f, 0x73, 0x30, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0e,
	0x71, 0x6f, 0x73, 0x30, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x3f,
	0x0a, 0x10, 0x71, 0x6f, 0x73, 0x31, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x0e, 0x71, 0x6f, 0x73, 0x31, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x36, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x1a, 0x38, 0x0a, 0x0a, 0x54, 0x6f, 0x70, 0x69, 0x63,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0x47, 0x0a, 0x10, 0x55, 0x6e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x22, 0x28, 0x0a, 0x12, 0x52, 0x65,
	0x74, 0x61, 0x69, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0xb6, 0x01, 0x0a, 0x17, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x3d,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x25,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a,
	0x09, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x22, 0x21, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x10, 0x00,
	0x12, 0x0b, 0x0a, 0x07, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x10, 0x01, 0x42, 0x26, 0x5a,
	0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6b, 0x7a, 0x6a,
	0x2f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x4f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_streamIO_proto_event_proto_rawDescOnce sync.Once
	file_streamIO_proto_event_proto_rawDescData = file_streamIO_proto_event_proto_rawDesc
)

func file_streamIO_proto_event_proto_rawDescGZIP() []byte {
	file_streamIO_proto_event_proto_rawDescOnce.Do(func() {
		file_streamIO_proto_event_proto_rawDescData = protoimpl.X.CompressGZIP(file_streamIO_proto_event_proto_rawDescData)
	})
	return file_streamIO_proto_event_proto_rawDescData
}

var file_streamIO_proto_event_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_streamIO_proto_event_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_streamIO_proto_event_proto_goTypes = []interface{}{
	(Event_Type)(0),                     // 0: proto.Event.Type
	(ClientStatusChangeEvent_Status)(0), // 1: proto.ClientStatusChangeEvent.Status
	(*Event)(nil),                       // 2: proto.Event
	(*SubscribeEvent)(nil),              // 3: proto.SubscribeEvent
	(*UnSubscribeEvent)(nil),            // 4: proto.UnSubscribeEvent
	(*RetainMessageEvent)(nil),          // 5: proto.RetainMessageEvent
	(*ClientStatusChangeEvent)(nil),     // 6: proto.ClientStatusChangeEvent
	nil,                                 // 7: proto.SubscribeEvent.TopicEntry
	(*StreamInfoItem)(nil),              // 8: proto.StreamInfoItem
}
var file_streamIO_proto_event_proto_depIdxs = []int32{
	0, // 0: proto.Event.type:type_name -> proto.Event.Type
	8, // 1: proto.SubscribeEvent.qos0_stream_info:type_name -> proto.StreamInfoItem
	8, // 2: proto.SubscribeEvent.qos1_stream_info:type_name -> proto.StreamInfoItem
	7, // 3: proto.SubscribeEvent.topic:type_name -> proto.SubscribeEvent.TopicEntry
	1, // 4: proto.ClientStatusChangeEvent.status:type_name -> proto.ClientStatusChangeEvent.Status
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_streamIO_proto_event_proto_init() }
func file_streamIO_proto_event_proto_init() {
	if File_streamIO_proto_event_proto != nil {
		return
	}
	file_streamIO_proto_items_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_streamIO_proto_event_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_streamIO_proto_event_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_streamIO_proto_event_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnSubscribeEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_streamIO_proto_event_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetainMessageEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_streamIO_proto_event_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientStatusChangeEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_streamIO_proto_event_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streamIO_proto_event_proto_goTypes,
		DependencyIndexes: file_streamIO_proto_event_proto_depIdxs,
		EnumInfos:         file_streamIO_proto_event_proto_enumTypes,
		MessageInfos:      file_streamIO_proto_event_proto_msgTypes,
	}.Build()
	File_streamIO_proto_event_proto = out.File
	file_streamIO_proto_event_proto_rawDesc = nil
	file_streamIO_proto_event_proto_goTypes = nil
	file_streamIO_proto_event_proto_depIdxs = nil
}
