// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: streamIO.proto

package streamIO

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AppendStreamResponse_Status int32

const (
	AppendStreamResponse_ok          AppendStreamResponse_Status = 0
	AppendStreamResponse_OffsetError AppendStreamResponse_Status = 1
)

// Enum value maps for AppendStreamResponse_Status.
var (
	AppendStreamResponse_Status_name = map[int32]string{
		0: "ok",
		1: "OffsetError",
	}
	AppendStreamResponse_Status_value = map[string]int32{
		"ok":          0,
		"OffsetError": 1,
	}
)

func (x AppendStreamResponse_Status) Enum() *AppendStreamResponse_Status {
	p := new(AppendStreamResponse_Status)
	*p = x
	return p
}

func (x AppendStreamResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AppendStreamResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_streamIO_proto_enumTypes[0].Descriptor()
}

func (AppendStreamResponse_Status) Type() protoreflect.EnumType {
	return &file_streamIO_proto_enumTypes[0]
}

func (x AppendStreamResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AppendStreamResponse_Status.Descriptor instead.
func (AppendStreamResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_streamIO_proto_rawDescGZIP(), []int{5, 0}
}

type SetStreamReadOffsetResponse_Status int32

const (
	SetStreamReadOffsetResponse_OK       SetStreamReadOffsetResponse_Status = 0
	SetStreamReadOffsetResponse_Conflict SetStreamReadOffsetResponse_Status = 1
)

// Enum value maps for SetStreamReadOffsetResponse_Status.
var (
	SetStreamReadOffsetResponse_Status_name = map[int32]string{
		0: "OK",
		1: "Conflict",
	}
	SetStreamReadOffsetResponse_Status_value = map[string]int32{
		"OK":       0,
		"Conflict": 1,
	}
)

func (x SetStreamReadOffsetResponse_Status) Enum() *SetStreamReadOffsetResponse_Status {
	p := new(SetStreamReadOffsetResponse_Status)
	*p = x
	return p
}

func (x SetStreamReadOffsetResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SetStreamReadOffsetResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_streamIO_proto_enumTypes[1].Descriptor()
}

func (SetStreamReadOffsetResponse_Status) Type() protoreflect.EnumType {
	return &file_streamIO_proto_enumTypes[1]
}

func (x SetStreamReadOffsetResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SetStreamReadOffsetResponse_Status.Descriptor instead.
func (SetStreamReadOffsetResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_streamIO_proto_rawDescGZIP(), []int{12, 0}
}

type ServerBase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Leader bool   `protobuf:"varint,2,opt,name=leader,proto3" json:"leader,omitempty"`
	Addr   string `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`
}

func (x *ServerBase) Reset() {
	*x = ServerBase{}
	if protoimpl.UnsafeEnabled {
		mi := &file_streamIO_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerBase) ProtoMessage() {}

func (x *ServerBase) ProtoReflect() protoreflect.Message {
	mi := &file_streamIO_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerBase.ProtoReflect.Descriptor instead.
func (*ServerBase) Descriptor() ([]byte, []int) {
	return file_streamIO_proto_rawDescGZIP(), []int{0}
}

func (x *ServerBase) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ServerBase) GetLeader() bool {
	if x != nil {
		return x.Leader
	}
	return false
}

func (x *ServerBase) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type StreamServer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base *ServerBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
}

func (x *StreamServer) Reset() {
	*x = StreamServer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_streamIO_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamServer) ProtoMessage() {}

func (x *StreamServer) ProtoReflect() protoreflect.Message {
	mi := &file_streamIO_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamServer.ProtoReflect.Descriptor instead.
func (*StreamServer) Descriptor() ([]byte, []int) {
	return file_streamIO_proto_rawDescGZIP(), []int{1}
}

func (x *StreamServer) GetBase() *ServerBase {
	if x != nil {
		return x.Base
	}
	return nil
}

type MetaServer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base *ServerBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
}

func (x *MetaServer) Reset() {
	*x = MetaServer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_streamIO_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetaServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaServer) ProtoMessage() {}

func (x *MetaServer) ProtoReflect() protoreflect.Message {
	mi := &file_streamIO_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaServer.ProtoReflect.Descriptor instead.
func (*MetaServer) Descriptor() ([]byte, []int) {
	return file_streamIO_proto_rawDescGZIP(), []int{2}
}

func (x *MetaServer) GetBase() *ServerBase {
	if x != nil {
		return x.Base
	}
	return nil
}

type StreamInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Begin int64  `protobuf:"varint,3,opt,name=begin,proto3" json:"begin,omitempty"`
	End   int64  `protobuf:"varint,4,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *StreamInfo) Reset() {
	*x = StreamInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_streamIO_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInfo) ProtoMessage() {}

func (x *StreamInfo) ProtoReflect() protoreflect.Message {
	mi := &file_streamIO_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamInfo.ProtoReflect.Descriptor instead.
func (*StreamInfo) Descriptor() ([]byte, []int) {
	return file_streamIO_proto_rawDescGZIP(), []int{3}
}

func (x *StreamInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StreamInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StreamInfo) GetBegin() int64 {
	if x != nil {
		return x.Begin
	}
	return 0
}

func (x *StreamInfo) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

//stream operator
type AppendStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Offset int64  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Data   []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *AppendStreamRequest) Reset() {
	*x = AppendStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_streamIO_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppendStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendStreamRequest) ProtoMessage() {}

func (x *AppendStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streamIO_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendStreamRequest.ProtoReflect.Descriptor instead.
func (*AppendStreamRequest) Descriptor() ([]byte, []int) {
	return file_streamIO_proto_rawDescGZIP(), []int{4}
}

func (x *AppendStreamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppendStreamRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *AppendStreamRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type AppendStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status AppendStreamResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=streamIO.AppendStreamResponse_Status" json:"status,omitempty"`
	Offset int64                       `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *AppendStreamResponse) Reset() {
	*x = AppendStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_streamIO_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppendStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendStreamResponse) ProtoMessage() {}

func (x *AppendStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streamIO_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendStreamResponse.ProtoReflect.Descriptor instead.
func (*AppendStreamResponse) Descriptor() ([]byte, []int) {
	return file_streamIO_proto_rawDescGZIP(), []int{5}
}

func (x *AppendStreamResponse) GetStatus() AppendStreamResponse_Status {
	if x != nil {
		return x.Status
	}
	return AppendStreamResponse_ok
}

func (x *AppendStreamResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ReadStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Offset int64  `protobuf:"varint,2,opt,name=Offset,proto3" json:"Offset,omitempty"`
	Length int32  `protobuf:"varint,3,opt,name=Length,proto3" json:"Length,omitempty"`
	Watch  bool   `protobuf:"varint,4,opt,name=Watch,proto3" json:"Watch,omitempty"`
}

func (x *ReadStreamRequest) Reset() {
	*x = ReadStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_streamIO_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStreamRequest) ProtoMessage() {}

func (x *ReadStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streamIO_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStreamRequest.ProtoReflect.Descriptor instead.
func (*ReadStreamRequest) Descriptor() ([]byte, []int) {
	return file_streamIO_proto_rawDescGZIP(), []int{6}
}

func (x *ReadStreamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReadStreamRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadStreamRequest) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *ReadStreamRequest) GetWatch() bool {
	if x != nil {
		return x.Watch
	}
	return false
}

type CreateStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateStreamRequest) Reset() {
	*x = CreateStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_streamIO_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStreamRequest) ProtoMessage() {}

func (x *CreateStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streamIO_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStreamRequest.ProtoReflect.Descriptor instead.
func (*CreateStreamRequest) Descriptor() ([]byte, []int) {
	return file_streamIO_proto_rawDescGZIP(), []int{7}
}

func (x *CreateStreamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info  *StreamInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Error string      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *CreateStreamResponse) Reset() {
	*x = CreateStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_streamIO_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStreamResponse) ProtoMessage() {}

func (x *CreateStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streamIO_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStreamResponse.ProtoReflect.Descriptor instead.
func (*CreateStreamResponse) Descriptor() ([]byte, []int) {
	return file_streamIO_proto_rawDescGZIP(), []int{8}
}

func (x *CreateStreamResponse) GetInfo() *StreamInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *CreateStreamResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetStreamInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *GetStreamInfoRequest) Reset() {
	*x = GetStreamInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_streamIO_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStreamInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamInfoRequest) ProtoMessage() {}

func (x *GetStreamInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streamIO_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamInfoRequest.ProtoReflect.Descriptor instead.
func (*GetStreamInfoRequest) Descriptor() ([]byte, []int) {
	return file_streamIO_proto_rawDescGZIP(), []int{9}
}

func (x *GetStreamInfoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetStreamInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info  *StreamInfo `protobuf:"bytes,1,opt,name=Info,proto3" json:"Info,omitempty"`
	Error string      `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (x *GetStreamInfoResponse) Reset() {
	*x = GetStreamInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_streamIO_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStreamInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamInfoResponse) ProtoMessage() {}

func (x *GetStreamInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streamIO_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamInfoResponse.ProtoReflect.Descriptor instead.
func (*GetStreamInfoResponse) Descriptor() ([]byte, []int) {
	return file_streamIO_proto_rawDescGZIP(), []int{10}
}

func (x *GetStreamInfoResponse) GetInfo() *StreamInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *GetStreamInfoResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SetStreamReadOffsetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offsets []*SetStreamReadOffsetRequest_Offset `protobuf:"bytes,1,rep,name=offsets,proto3" json:"offsets,omitempty"`
}

func (x *SetStreamReadOffsetRequest) Reset() {
	*x = SetStreamReadOffsetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_streamIO_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetStreamReadOffsetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStreamReadOffsetRequest) ProtoMessage() {}

func (x *SetStreamReadOffsetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streamIO_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStreamReadOffsetRequest.ProtoReflect.Descriptor instead.
func (*SetStreamReadOffsetRequest) Descriptor() ([]byte, []int) {
	return file_streamIO_proto_rawDescGZIP(), []int{11}
}

func (x *SetStreamReadOffsetRequest) GetOffsets() []*SetStreamReadOffsetRequest_Offset {
	if x != nil {
		return x.Offsets
	}
	return nil
}

type SetStreamReadOffsetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status SetStreamReadOffsetResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=streamIO.SetStreamReadOffsetResponse_Status" json:"status,omitempty"`
}

func (x *SetStreamReadOffsetResponse) Reset() {
	*x = SetStreamReadOffsetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_streamIO_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetStreamReadOffsetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStreamReadOffsetResponse) ProtoMessage() {}

func (x *SetStreamReadOffsetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streamIO_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStreamReadOffsetResponse.ProtoReflect.Descriptor instead.
func (*SetStreamReadOffsetResponse) Descriptor() ([]byte, []int) {
	return file_streamIO_proto_rawDescGZIP(), []int{12}
}

func (x *SetStreamReadOffsetResponse) GetStatus() SetStreamReadOffsetResponse_Status {
	if x != nil {
		return x.Status
	}
	return SetStreamReadOffsetResponse_OK
}

type GetStreamReadOffsetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId int64 `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StreamId  int64 `protobuf:"varint,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
}

func (x *GetStreamReadOffsetRequest) Reset() {
	*x = GetStreamReadOffsetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_streamIO_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStreamReadOffsetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamReadOffsetRequest) ProtoMessage() {}

func (x *GetStreamReadOffsetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streamIO_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamReadOffsetRequest.ProtoReflect.Descriptor instead.
func (*GetStreamReadOffsetRequest) Descriptor() ([]byte, []int) {
	return file_streamIO_proto_rawDescGZIP(), []int{13}
}

func (x *GetStreamReadOffsetRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *GetStreamReadOffsetRequest) GetStreamId() int64 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

type SetStreamReadOffsetRequest_Offset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId int64 `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StreamId  int64 `protobuf:"varint,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Offset    int64 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *SetStreamReadOffsetRequest_Offset) Reset() {
	*x = SetStreamReadOffsetRequest_Offset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_streamIO_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetStreamReadOffsetRequest_Offset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStreamReadOffsetRequest_Offset) ProtoMessage() {}

func (x *SetStreamReadOffsetRequest_Offset) ProtoReflect() protoreflect.Message {
	mi := &file_streamIO_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStreamReadOffsetRequest_Offset.ProtoReflect.Descriptor instead.
func (*SetStreamReadOffsetRequest_Offset) Descriptor() ([]byte, []int) {
	return file_streamIO_proto_rawDescGZIP(), []int{11, 0}
}

func (x *SetStreamReadOffsetRequest_Offset) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *SetStreamReadOffsetRequest_Offset) GetStreamId() int64 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *SetStreamReadOffsetRequest_Offset) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

var File_streamIO_proto protoreflect.FileDescriptor

var file_streamIO_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x4f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x4f, 0x22, 0x48, 0x0a, 0x0a, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x42, 0x61, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x61, 0x64, 0x64, 0x72, 0x22, 0x38, 0x0a, 0x0c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x4f, 0x2e, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x42, 0x61, 0x73, 0x65, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x22, 0x36,
	0x0a, 0x0a, 0x4d, 0x65, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x04,
	0x62, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x49, 0x4f, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x42, 0x61, 0x73, 0x65,
	0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x22, 0x58, 0x0a, 0x0a, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x65, 0x67, 0x69,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x12, 0x10,
	0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x65, 0x6e, 0x64,
	0x22, 0x55, 0x0a, 0x13, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f,
	0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x90, 0x01, 0x0a, 0x14, 0x41, 0x70, 0x70, 0x65,
	0x6e, 0x64, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3d, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x25, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x4f, 0x2e, 0x41, 0x70, 0x70, 0x65,
	0x6e, 0x64, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x21, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x06, 0x0a, 0x02, 0x6f, 0x6b, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x4f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x01, 0x22, 0x6d, 0x0a, 0x11, 0x52, 0x65,
	0x61, 0x64, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x4c,
	0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x4c, 0x65, 0x6e,
	0x67, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x57, 0x61, 0x74, 0x63, 0x68, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x05, 0x57, 0x61, 0x74, 0x63, 0x68, 0x22, 0x29, 0x0a, 0x13, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x56, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x04,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x49, 0x4f, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x2a, 0x0a, 0x14,
	0x47, 0x65, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x57, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x28, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x4f, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x22, 0xc1, 0x01, 0x0a, 0x1a, 0x53, 0x65, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52,
	0x65, 0x61, 0x64, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x45, 0x0a, 0x07, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x2b, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x4f, 0x2e, 0x53, 0x65, 0x74,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x61, 0x64, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x52, 0x07,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x73, 0x1a, 0x5c, 0x0a, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f,
	0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x83, 0x01, 0x0a, 0x1b, 0x53, 0x65, 0x74, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x52, 0x65, 0x61, 0x64, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2c, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x4f,
	0x2e, 0x53, 0x65, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x61, 0x64, 0x4f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x1e, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x0c, 0x0a,
	0x08, 0x43, 0x6f, 0x6e, 0x66, 0x6c, 0x69, 0x63, 0x74, 0x10, 0x01, 0x22, 0x58, 0x0a, 0x1a, 0x47,
	0x65, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x61, 0x64, 0x4f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x49, 0x64, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x73, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x49, 0x4f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_streamIO_proto_rawDescOnce sync.Once
	file_streamIO_proto_rawDescData = file_streamIO_proto_rawDesc
)

func file_streamIO_proto_rawDescGZIP() []byte {
	file_streamIO_proto_rawDescOnce.Do(func() {
		file_streamIO_proto_rawDescData = protoimpl.X.CompressGZIP(file_streamIO_proto_rawDescData)
	})
	return file_streamIO_proto_rawDescData
}

var file_streamIO_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_streamIO_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_streamIO_proto_goTypes = []interface{}{
	(AppendStreamResponse_Status)(0),          // 0: streamIO.AppendStreamResponse.Status
	(SetStreamReadOffsetResponse_Status)(0),   // 1: streamIO.SetStreamReadOffsetResponse.Status
	(*ServerBase)(nil),                        // 2: streamIO.ServerBase
	(*StreamServer)(nil),                      // 3: streamIO.StreamServer
	(*MetaServer)(nil),                        // 4: streamIO.MetaServer
	(*StreamInfo)(nil),                        // 5: streamIO.StreamInfo
	(*AppendStreamRequest)(nil),               // 6: streamIO.AppendStreamRequest
	(*AppendStreamResponse)(nil),              // 7: streamIO.AppendStreamResponse
	(*ReadStreamRequest)(nil),                 // 8: streamIO.ReadStreamRequest
	(*CreateStreamRequest)(nil),               // 9: streamIO.CreateStreamRequest
	(*CreateStreamResponse)(nil),              // 10: streamIO.CreateStreamResponse
	(*GetStreamInfoRequest)(nil),              // 11: streamIO.GetStreamInfoRequest
	(*GetStreamInfoResponse)(nil),             // 12: streamIO.GetStreamInfoResponse
	(*SetStreamReadOffsetRequest)(nil),        // 13: streamIO.SetStreamReadOffsetRequest
	(*SetStreamReadOffsetResponse)(nil),       // 14: streamIO.SetStreamReadOffsetResponse
	(*GetStreamReadOffsetRequest)(nil),        // 15: streamIO.GetStreamReadOffsetRequest
	(*SetStreamReadOffsetRequest_Offset)(nil), // 16: streamIO.SetStreamReadOffsetRequest.Offset
}
var file_streamIO_proto_depIdxs = []int32{
	2,  // 0: streamIO.StreamServer.base:type_name -> streamIO.ServerBase
	2,  // 1: streamIO.MetaServer.base:type_name -> streamIO.ServerBase
	0,  // 2: streamIO.AppendStreamResponse.status:type_name -> streamIO.AppendStreamResponse.Status
	5,  // 3: streamIO.CreateStreamResponse.info:type_name -> streamIO.StreamInfo
	5,  // 4: streamIO.GetStreamInfoResponse.Info:type_name -> streamIO.StreamInfo
	16, // 5: streamIO.SetStreamReadOffsetRequest.offsets:type_name -> streamIO.SetStreamReadOffsetRequest.Offset
	1,  // 6: streamIO.SetStreamReadOffsetResponse.status:type_name -> streamIO.SetStreamReadOffsetResponse.Status
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_streamIO_proto_init() }
func file_streamIO_proto_init() {
	if File_streamIO_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_streamIO_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerBase); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_streamIO_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamServer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_streamIO_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetaServer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_streamIO_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_streamIO_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppendStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_streamIO_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppendStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_streamIO_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_streamIO_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_streamIO_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_streamIO_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStreamInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_streamIO_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStreamInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_streamIO_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetStreamReadOffsetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_streamIO_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetStreamReadOffsetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_streamIO_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStreamReadOffsetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_streamIO_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetStreamReadOffsetRequest_Offset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_streamIO_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streamIO_proto_goTypes,
		DependencyIndexes: file_streamIO_proto_depIdxs,
		EnumInfos:         file_streamIO_proto_enumTypes,
		MessageInfos:      file_streamIO_proto_msgTypes,
	}.Build()
	File_streamIO_proto = out.File
	file_streamIO_proto_rawDesc = nil
	file_streamIO_proto_goTypes = nil
	file_streamIO_proto_depIdxs = nil
}
